"""Initial migration

Revision ID: e9cb4736c251
Revises: 849707822eaa
Create Date: 2024-12-05 01:11:18.938934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9cb4736c251'
down_revision: Union[str, None] = '849707822eaa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LtRole',
    sa.Column('RoleID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=36), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('RoleID')
    )
    op.create_table('LtWaterProperty',
    sa.Column('WaterPropertyID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=36), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('WaterPropertyID')
    )
    op.create_table('LtWaterQuality',
    sa.Column('WaterQualityID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('WaterQualityID')
    )
    op.create_table('MsCompany',
    sa.Column('CompanyID', sa.String(length=36), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.Column('Description', sa.Text(), nullable=True),
    sa.Column('Address', sa.String(length=255), nullable=False),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('PhoneNumber', sa.String(length=20), nullable=False),
    sa.Column('Website', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('CompanyID')
    )
    op.create_table('MsProduct',
    sa.Column('ProductID', sa.String(length=36), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=False),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.Column('Image', sa.Text(), nullable=True),
    sa.Column('CompanyID', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['CompanyID'], ['MsCompany.CompanyID'], ),
    sa.PrimaryKeyConstraint('ProductID')
    )
    op.create_table('MsUser',
    sa.Column('UserID', sa.String(length=36), nullable=False),
    sa.Column('FirstName', sa.String(length=36), nullable=True),
    sa.Column('LastName', sa.String(length=36), nullable=True),
    sa.Column('Email', sa.String(length=255), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.Column('Role', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Role'], ['LtRole.RoleID'], ),
    sa.PrimaryKeyConstraint('UserID'),
    sa.UniqueConstraint('Email')
    )
    op.create_table('MsUserCompanyMapping',
    sa.Column('UserCompanyID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.String(length=36), nullable=True),
    sa.Column('CompanyID', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['CompanyID'], ['MsCompany.CompanyID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['MsUser.UserID'], ),
    sa.PrimaryKeyConstraint('UserCompanyID')
    )
    op.create_table('TrWaterData',
    sa.Column('WaterDataID', sa.Integer(), nullable=False),
    sa.Column('ProductID', sa.String(length=36), nullable=True),
    sa.Column('Date', sa.DateTime(), nullable=False),
    sa.Column('Image', sa.Text(), nullable=True),
    sa.Column('Description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['ProductID'], ['MsProduct.ProductID'], ),
    sa.PrimaryKeyConstraint('WaterDataID')
    )
    op.create_table('TrWaterDataDetail',
    sa.Column('WaterDataDetailID', sa.Integer(), nullable=False),
    sa.Column('WaterDataID', sa.Integer(), nullable=True),
    sa.Column('WaterPropertyID', sa.Integer(), nullable=True),
    sa.Column('Value', sa.DECIMAL(), nullable=False),
    sa.ForeignKeyConstraint(['WaterDataID'], ['TrWaterData.WaterDataID'], ),
    sa.ForeignKeyConstraint(['WaterPropertyID'], ['LtWaterProperty.WaterPropertyID'], ),
    sa.PrimaryKeyConstraint('WaterDataDetailID')
    )
    op.create_table('TrWaterQualityPrediction',
    sa.Column('WaterQualityPredictionID', sa.Integer(), nullable=False),
    sa.Column('WaterDataID', sa.Integer(), nullable=True),
    sa.Column('WaterQualityID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['WaterDataID'], ['TrWaterData.WaterDataID'], ),
    sa.ForeignKeyConstraint(['WaterQualityID'], ['LtWaterQuality.WaterQualityID'], ),
    sa.PrimaryKeyConstraint('WaterQualityPredictionID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TrWaterQualityPrediction')
    op.drop_table('TrWaterDataDetail')
    op.drop_table('TrWaterData')
    op.drop_table('MsUserCompanyMapping')
    op.drop_table('MsUser')
    op.drop_table('MsProduct')
    op.drop_table('MsCompany')
    op.drop_table('LtWaterQuality')
    op.drop_table('LtWaterProperty')
    op.drop_table('LtRole')
    # ### end Alembic commands ###
